<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Permission\Control;

use Drago;


class UsersRolesEntity extends Drago\Database\Entity
{
	public const string
		Table = 'users_roles',
		ColumnUserId = 'user_id',
		ColumnRoleId = 'role_id';

	/** Column size 10 */
	public int $user_id;

	/** Column size 10 */
	public int $role_id;
}
