<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Permission\Control;

use Drago;


class UsersEntity extends Drago\Database\Entity
{
	public const string
		Table = 'users',
		PrimaryKey = 'id',
		ColumnUsername = 'username';

	/**
	 * Primary key
	 * Column size 10
	 */
	public int $id;

	/** Column size 50 */
	public string $username;
}
