<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Permission\Control;

use Drago;


class RolesEntity extends Drago\Database\Entity
{
	public const string
		Table = 'roles',
		PrimaryKey = 'id',
		ColumnName = 'name',
		ColumnRole = 'role';

	/**
	 * Primary key
	 * Column size 10
	 */
	public int $id;

	/** Column size 40 */
	public string $name;

	/** Column size 40 */
	public string $role;
}
